# Generated by Django 3.2 on 2021-05-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210513_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='content',
            new_name='queries',
        ),
    ]
