# Generated by Django 3.2 on 2021-05-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210513_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin',
            field=models.DateTimeField(blank=True, help_text='Check in', null=True),
        ),
    ]
