# Generated by Django 3.2 on 2021-05-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210513_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timeStamp',
            field=models.DateTimeField(blank=True),
        ),
    ]
