# Generated by Django 3.2 on 2021-05-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_timestamp_booking_requestsent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='requestsent',
            new_name='timeStamp',
        ),
    ]
